import { compileAgent } from "@/lib/agent/compile";
import { KIND_META, TOOL_CATALOG, type AgentGraph } from "@/lib/agent/types";
import type { FileMap, Plan } from "@/lib/ai/schema";

// Documents generated from what the project actually contains: the latest plan, the agent graph
// and the files. Nothing here is canned; sections without data say so.

export type ArtifactInput = { name: string; plan?: Plan; agent?: { name: string; graph: AgentGraph } | null; files: FileMap };

const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
const list = (items: string[], empty: string) => (items.length ? items.map((i) => `- ${i}`).join("\n") : `_${empty}_`);
const today = () => new Date().toISOString().slice(0, 10);

function agentFacts(input: ArtifactInput) {
  if (!input.agent) return null;
  const spec = compileAgent(input.agent.graph, input.agent.name);
  const tools = spec.tools.map((id) => {
    const meta = TOOL_CATALOG.find((t) => t.id === id);
    return `${meta?.label ?? id}${meta?.live ? "" : " (simulated until connected)"}`;
  });
  const blocks = input.agent.graph.nodes.map((n) => `${KIND_META[n.data.kind]?.pro ?? n.data.kind}: ${n.data.label}`);
  return { spec, tools, blocks };
}

export function reportMarkdown(input: ArtifactInput) {
  const { plan, files } = input;
  const agent = agentFacts(input);
  const paths = Object.keys(files).sort();
  return [
    `# ${input.name}: project report`,
    `_Generated by Architect on ${today()} from the current plan, agent and files._`,
    `## Summary`,
    plan?.summary ?? "_No plan yet. Describe the app in the chat to get one._",
    `## Screens`,
    plan?.screens.length ? ["| Screen | Purpose |", "|---|---|", ...plan.screens.map((s) => `| ${cell(s.name)} | ${cell(s.purpose)} |`)].join("\n") : "_None planned._",
    `## Data model`,
    plan?.data.length ? ["| Record | Fields |", "|---|---|", ...plan.data.map((d) => `| ${cell(d.entity)} | ${cell(d.fields.join(", "))} |`)].join("\n") : "_None planned._",
    `## Agent`,
    agent
      ? [
          `**${input.agent!.name}** runs on ${agent.spec.model}.`,
          `**Steps**\n${list(plan?.agent.steps ?? [], "Not described in the plan.")}`,
          `**Tools**\n${list(agent.tools, "No tools.")}`,
          `**Rules**\n${list(agent.spec.rules, "No guardrail rules.")}`,
          `**Blocks on the canvas**\n${list(agent.blocks, "Empty canvas.")}`,
        ].join("\n\n")
      : plan
        ? `**${plan.agent.name}**: ${plan.agent.goal}\n\n${list(plan.agent.steps, "No steps.")}\n\n_The agent hasn't been created yet; open the Agent tab._`
        : "_No agent yet._",
    `## Integrations`,
    list(plan?.integrations ?? [], "None."),
    `## Assumptions`,
    list(plan?.assumptions ?? [], "None recorded."),
    `## Files (${paths.length})`,
    list(paths.map((p) => `\`${p}\``), "Nothing built yet."),
  ].join("\n\n");
}

export function deckMarkdown(input: ArtifactInput) {
  const { plan } = input;
  const agent = agentFacts(input);
  return [
    `# ${input.name}: deck outline`,
    `## 1. The problem`,
    plan ? `- ${plan.summary}` : "- _Describe the app in the chat to fill this in._",
    `## 2. What we built`,
    list(plan?.screens.map((s) => `**${s.name}**: ${s.purpose}`) ?? [], "No screens yet."),
    `## 3. How the agent works`,
    list(plan?.agent.steps ?? [], "No agent steps yet."),
    `## 4. What it connects to`,
    list([...(plan?.integrations ?? []), ...(agent?.tools ?? [])], "Nothing yet."),
    `## 5. Guardrails`,
    list(agent?.spec.rules ?? plan?.rules ?? [], "No rules yet."),
    `## 6. Demo`,
    "- Show the live preview, then run the agent in the test console.",
    `## 7. Open questions`,
    list(plan?.assumptions ?? [], "None."),
  ].join("\n\n");
}

export function specMarkdown(input: ArtifactInput) {
  const { plan } = input;
  return [
    `# ${input.name}: product spec`,
    `**Status:** Draft · **Date:** ${today()}`,
    `## Problem and outcome`,
    plan?.summary ?? "_No plan yet._",
    `## Screens and flows`,
    list(plan?.screens.map((s) => `**${s.name}**: ${s.purpose}`) ?? [], "None planned."),
    `## Data`,
    list(plan?.data.map((d) => `**${d.entity}**: ${d.fields.join(", ")}`) ?? [], "None planned."),
    `## Agent behaviour`,
    plan ? `${plan.agent.goal}\n\n${list(plan.agent.steps, "No steps.")}` : "_None._",
    `## Rules the agent follows`,
    list(plan?.rules ?? [], "None."),
    `## Integrations`,
    list(plan?.integrations ?? [], "None."),
    `## Assumptions to validate`,
    list(plan?.assumptions ?? [], "None."),
  ].join("\n\n");
}

const csv = (v: string) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);

/** The planned data model, one row per field, for Excel or Google Sheets. */
export function dataModelCsv(input: ArtifactInput) {
  const rows = (input.plan?.data ?? []).flatMap((d) => (d.fields.length ? d.fields : [""]).map((f) => [d.entity, f]));
  return [["record", "field"], ...rows].map((r) => r.map(csv).join(",")).join("\n");
}
